//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "crawl_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub start_url: String,
    #[sea_orm(ignore, column_type = "custom(\"datetime\")", select_as = "text")]
    pub started_at: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"datetime\")",
        select_as = "text",
        nullable
    )]
    pub completed_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub pages_crawled: i64,
    pub errors_encountered: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pages::Entity")]
    Pages,
    #[sea_orm(has_many = "super::url_queue::Entity")]
    UrlQueue,
}

impl Related<super::pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pages.def()
    }
}

impl Related<super::url_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UrlQueue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
