//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "domains")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub domain: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub robots_txt: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub crawl_delay: Option<f64>,
    pub allow_crawl: bool,
    #[sea_orm(
        ignore,
        column_type = "custom(\"datetime\")",
        select_as = "text",
        nullable
    )]
    pub last_robots_check: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
