//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "links")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub source_page_id: i64,
    #[sea_orm(column_type = "Text")]
    pub target_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub link_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub link_type: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"datetime\")", select_as = "text")]
    pub discovered_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pages::Entity",
        from = "Column::SourcePageId",
        to = "super::pages::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Pages,
}

impl Related<super::pages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
