//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub crawl_session_id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_hash: Option<String>,
    pub status_code: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_type: Option<String>,
    pub content_length: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"datetime\")", select_as = "text")]
    pub crawled_at: String,
    #[sea_orm(
        ignore,
        column_type = "custom(\"datetime\")",
        select_as = "text",
        nullable
    )]
    pub last_modified: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::crawl_sessions::Entity",
        from = "Column::CrawlSessionId",
        to = "super::crawl_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CrawlSessions,
    #[sea_orm(has_many = "super::links::Entity")]
    Links,
}

impl Related<super::crawl_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrawlSessions.def()
    }
}

impl Related<super::links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Links.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
