//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::crawl_sessions::Entity as CrawlSessions;
pub use super::domains::Entity as Domains;
pub use super::links::Entity as Links;
pub use super::pages::Entity as Pages;
pub use super::url_queue::Entity as UrlQueue;
