//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "url_queue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub crawl_session_id: i64,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub priority: i64,
    pub retry_count: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(ignore, column_type = "custom(\"datetime\")", select_as = "text")]
    pub queued_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::crawl_sessions::Entity",
        from = "Column::CrawlSessionId",
        to = "super::crawl_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CrawlSessions,
}

impl Related<super::crawl_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrawlSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
